### ISSUE TITLE
Nullpointer Exception in CertJudger

### ISSUE THREAD

**Issue by ic0ns** [RUB-NDS/TLS-Scanner#19]
Exception in thread "Thread-208" java.lang.NullPointerException
	at de.rub.nds.tlsscanner.probe.certificate.CertificateJudger.isWeakHashAlgo(CertificateJudger.java:58)
	at de.rub.nds.tlsscanner.report.result.CertificateResult.merge(CertificateResult.java:46)
	at de.rub.nds.tlsscanner.ScanJobExecutor.execute(ScanJobExecutor.java:66)
	at de.rub.nds.tlsscanner.TlsScanner.scan(TlsScanner.java:97)

**Comment by ic0ns** [comment]
will be fixed in the next release 2.2
